theme: jekyll-swiss
title: Navigating Through Genres
description: Uncovering the Key Factors Behind Box Office Revenue throughout Movie Categories
theme_color: yellow

github_repo: ada-2023-project-topfive
github_username: epfl-ada


markdown: kramdown
